### ISSUE TITLE
Exilence ignore Tattoo's and Omen's. Can you add them?

### ISSUE THREAD

**Issue by Asag321** [exilence-ce/exilence-ce#1]
**Is your feature request related to a problem? Please describe.**
Exilence ignore tattoo's and omens in stash. With TOTA league we get many tattoo's and its annoying to manually checking how much they are worth. 

**Describe the solution you'd like**
Make them visible for Exilence?

**Comment by thepapanoob** [comment]
Hi! 

thank you for letting me know i didnt even realize it yet :) ill see what i can do

**Comment by thepapanoob** [comment]
Hi! 

i just released a new version: v1.2.3 wich has tattoo support added :) 
feel free to download and use it.

for anyone interested the commit a92b7a2 implemented it.
