### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Odin099** [exilence-ce/exilence-ce#16]
**Describe the bug**
i can't install it on win11. ALL versions have this issue!

1. if i try to start the .exe, win11 say it is an unsave app!!!
2. if i still start it stop installing about half way with an error:
https://imgur.com/AXFohWi

if i hit retry it goes on but stop with an error again:
https://imgur.com/lII6RVu

no idea why but it seems to try to overwrite its own uninstall.exe during installation but can't, what leads to an edless loop i guess.

if i click ignore, it goes on but ends up with not installing anything but creating a shortcut to nowhere on desctop.

**Comment by thepapanoob** [comment]
try uninstalling the old version first. then it should work :)

**Comment by Odin099** [comment]
oh i complete forgot this post but i did just that a week before.
i hope this will help others with the same issue:
first i deleted the whole files back in december (BIG MISTAKE) and windows 11 was unable to uninstall the old exilence because of the missing uninstaller. but last week i decidet to try uninstalling again but this time with "Revo uninstaller" (free uninstaller app) and with this i was able to also rewmove some leftover registry entrys and after that the installation worked just fine.
