### ISSUE TITLE
Invalid date format

### ISSUE THREAD

**Issue by sanfair** [exilence-ce/exilence-ce#17]
Invalid format for data in a few files:

- https://github.com/exilence-ce/exilence-ce/blob/84ad72d4fa8200b4e104f26617969e24691b4a60/src/components/item-table/ItemTableContainer.tsx#L240
- https://github.com/exilence-ce/exilence-ce/blob/84ad72d4fa8200b4e104f26617969e24691b4a60/src/components/remove-snapshots-dialog/RemoveSnapshotsDialog.tsx#L98-L100
- https://github.com/exilence-ce/exilence-ce/blob/84ad72d4fa8200b4e104f26617969e24691b4a60/src/utils/export.utils.ts#L11
- https://github.com/exilence-ce/exilence-ce/blob/84ad72d4fa8200b4e104f26617969e24691b4a60/src/utils/export.utils.ts#L14

Format set as `YYYY-MM-DD HH:MM` and will formate date "Dec 25 2023 18:57:05" as `2023-11-25 18:25`

Formant needs to be updated to `YYYY-MM-DD HH:mm`

**Comment by thepapanoob** [comment]
Thank you! this is fixed now!
