### ISSUE TITLE
il8n translations only display key not value (e.g. label.asking_price)

### ISSUE THREAD

**Issue by ASemiSeriousName** [exilence-ce/exilence-ce#5]
**Describe the bug**
Text for translations is displayed as labels instead of the value. E.g. `label.generate_image` instead of `Generate image` or whatever it's meant to be. It is happening in version 1.2.4 on Windows 10.

**To Reproduce**
1. Go to download and install version 1.2.4 on Windows and open the applications, it is happening everywhere

**Expected behavior**
The actual message is displayed instead of the translation key

**Screenshots**
![image](https://github.com/exilence-ce/exilence-ce/assets/47337589/398c1e34-0a90-4f67-828c-b0601bbf4f86)

**Version**
1.2.4

**Additional context**
Thanks for getting Exilence back up and running :)

**Comment by soham02** [comment]
+1 Can verify and reproduce the bug.
![image](https://github.com/exilence-ce/exilence-ce/assets/20030637/e45b3d1a-56d8-4a79-8177-4a29817c74c6)

**Comment by thepapanoob** [comment]
Yea i totally messed something up in the windows build... sorry for that. the update is expected in the next hour

**Comment by thepapanoob** [comment]
Forgot to update this issue thread: its fixed! The release v1.2.5 works on all 3 supported platforms equally well! The commit 299a7cbl was what fixed it in the end.
